# Generated by Django 5.2.4 on 2025-08-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('idade', models.CharField(max_length=20)),
                ('personagem', models.CharField(max_length=80)),
                ('nascimento', models.DateField()),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('conteudo', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'Atores',
            },
        ),
    ]
