# Generated by Django 5.2.4 on 2025-09-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sobre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(upload_to='imagens-carrossel')),
            ],
            options={
                'verbose_name_plural': 'Carrossel',
            },
        ),
    ]
