# Generated by Django 5.2.4 on 2025-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_carrossel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ator',
            name='imagem',
            field=models.ImageField(upload_to='imagens-ator/'),
        ),
        migrations.AlterField(
            model_name='elenco',
            name='imagem_e',
            field=models.ImageField(upload_to='imagens-elenco/'),
        ),
        migrations.AlterField(
            model_name='index',
            name='banner',
            field=models.ImageField(upload_to='imagens-banner/'),
        ),
    ]
